In [1]:
import numpy as np

simple_features = np.array([
    [1, 1, 1],
    [2, 2, 2],
    [3, 3, 3],
    [4, 4, 4],
    [5, 5, 5],
    [6, 6, 6],
    [7, 7, 7],
    [8, 8, 8],
    [9, 9, 9],
    [10, 10, 10],
    [11, 11, 11],
    [12, 12, 12],
])

simple_labels = np.array([
    [-1, -1],
    [-2, -2],
    [-3, -3],
    [-4, -4],
    [-5, -5],
    [-6, -6],
    [-7, -7],
    [-8, -8],
    [-9, -9],
    [-10, -10],
    [-11, -11],
    [-12, -12],
])

In [7]:
def print_dataset(ds):

    for inputs, targets in ds:
        print("---Batch---")
        print("Feature:", inputs.numpy())
        print("Label:", targets.numpy())
        print("")

def print_generator(gen):
    for inputs, targets in gen:
        print("---Batch---")
        print("Feature:", inputs)
        print("Label:", targets)
        print("")

In [3]:
import tensorflow as tf

2023-01-11 16:10:54.536460: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-01-11 16:10:54.536556: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory
2023-01-11 16:10:54.536569: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.


In [4]:
def timeseries_generator_one_step(features, labels, input_sequence_length, batch_size):
    return tf.keras.preprocessing.sequence.TimeseriesGenerator(
        features, 
        labels, 
        input_sequence_length, 
        batch_size=batch_size)

In [5]:
ds = tf.keras.preprocessing.timeseries_dataset_from_array(
    simple_features,
    simple_labels,
    sequence_length=4,
    batch_size=2)

2023-01-11 16:11:05.882339: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1613] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 28 MB memory:  -> device: 0, name: NVIDIA GeForce GTX 1060 3GB, pci bus id: 0000:01:00.0, compute capability: 6.1


In [8]:
print_dataset(ds)

---Batch---
Input shape = 
Feature: [[[1 1 1]
  [2 2 2]
  [3 3 3]
  [4 4 4]]

 [[2 2 2]
  [3 3 3]
  [4 4 4]
  [5 5 5]]]
Label: [[-1 -1]
 [-2 -2]]

---Batch---
Input shape = 
Feature: [[[3 3 3]
  [4 4 4]
  [5 5 5]
  [6 6 6]]

 [[4 4 4]
  [5 5 5]
  [6 6 6]
  [7 7 7]]]
Label: [[-3 -3]
 [-4 -4]]

---Batch---
Input shape = 
Feature: [[[5 5 5]
  [6 6 6]
  [7 7 7]
  [8 8 8]]

 [[6 6 6]
  [7 7 7]
  [8 8 8]
  [9 9 9]]]
Label: [[-5 -5]
 [-6 -6]]

---Batch---
Input shape = 
Feature: [[[ 7  7  7]
  [ 8  8  8]
  [ 9  9  9]
  [10 10 10]]

 [[ 8  8  8]
  [ 9  9  9]
  [10 10 10]
  [11 11 11]]]
Label: [[-7 -7]
 [-8 -8]]

---Batch---
Input shape = 
Feature: [[[ 9  9  9]
  [10 10 10]
  [11 11 11]
  [12 12 12]]]
Label: [[-9 -9]]



In [9]:
ds

<BatchDataset element_spec=(TensorSpec(shape=(None, None, 3), dtype=tf.int64, name=None), TensorSpec(shape=(None, 2), dtype=tf.int64, name=None))>

In [10]:
for (inputs, targets) in ds:
    print(inputs.shape)

(2, 4, 3)
(2, 4, 3)
(2, 4, 3)
(2, 4, 3)
(1, 4, 3)
